# Assignment 4: Cognitive Computing
**Nimish Badgujar**
**102497027**
---

## Question 1
Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [19]:
import numpy as np

nums = np.array([1,2,3,4,5])
print(f"Original: {nums}")
added = nums + 2
multiplied = nums * 3
divided = nums / 2
print(f"After Addition of 2: {added}\nAfter Multiplication by 3: {multiplied}\nAfter Division by 2: {divided}")

Original: [1 2 3 4 5]
After Addition of 2: [3 4 5 6 7]
After Multiplication by 3: [ 3  6  9 12 15]
After Division by 2: [0.5 1.  1.5 2.  2.5]


## Question 2
Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [20]:
import numpy as np
orig_arr = np.array([1,2,3,4,5])
rev_arr = orig_arr[::-1]
print(f"Reversed Array: {rev_arr}")

Reversed Array: [5 4 3 2 1]


In [21]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
freq_x = np.bincount(x).argmax()
idx_x = np.where(x == freq_x)[0]
y = np.array([1,1,1,2,3,4,2,4,3,3])
freq_y = np.bincount(y).argmax()
idx_y = np.where(y == freq_y)[0]
print(f"For x -> value: {freq_x}, indices: {idx_x}")
print(f"For y -> value: {freq_y}, indices: {idx_y}")

For x -> value: 1, indices: [0 5 7 8 9]
For y -> value: 1, indices: [0 1 2]


## Question 3
For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [22]:
import numpy as np

matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
first_row_second_col = matrix[0,1]
third_row_first_col = matrix[2,0]
print(f"(1st row, 2nd col): {first_row_second_col}")
print(f"(3rd row, 1st col): {third_row_first_col}")

(1st row, 2nd col): 20
(3rd row, 1st col): 70


## Question 4
Write a program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [23]:
import numpy as np

nimish = np.linspace(10, 100, 25)
d_count = nimish.ndim
dim_shape = nimish.shape
elem_total = nimish.size
dtype_info = nimish.dtype
b_count = nimish.nbytes
print(f"Array: {nimish}\nDimensions: {d_count}\nShape: {dim_shape}\nTotal: {elem_total}\nType: {dtype_info}\nBytes: {b_count}")
reshaped = nimish.reshape(25, 1)
print("Transpose via reshape:\n", reshaped)
print("Transpose via T attribute:\n", nimish.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total: 25
Type: float64
Bytes: 200
Transpose via reshape:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose via T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


## Question 5
Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [24]:
import numpy as np

ucs420_nimish = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
arr_mean = np.mean(ucs420_nimish)
arr_median = np.median(ucs420_nimish)
arr_max = np.max(ucs420_nimish)
arr_min = np.min(ucs420_nimish)
arr_unique = np.unique(ucs420_nimish)
print(f"Mean: {arr_mean}\nMedian: {arr_median}\nMax: {arr_max}\nMin: {arr_min}\nUnique: {arr_unique}")
reshaped_nimish = ucs420_nimish.reshape(4,3)
print("Reshaped (4x3):\n", reshaped_nimish)
resized_nimish = np.resize(ucs420_nimish, (2,3))
print("Resized (2x3):\n", resized_nimish)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized (2x3):
 [[10 20 30]
 [40 50 60]]
